services:
  - type: web
    name: colon-cancer-api
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.10.12